# Generated by Django 5.1.3 on 2024-11-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=50)),
                ('message', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
