# Generated by Django 5.1.3 on 2024-11-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_customer_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='session',
        ),
    ]
