# Generated by Django 5.1.3 on 2024-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, help_text='Session ID for anonymous users', max_length=255, null=True, unique=True),
        ),
    ]
