# Generated by Django 5.1.3 on 2024-11-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_cart_session'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.OneToOneField(blank=True, help_text='Session ID for anonymous users', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
