# Generated by Django 5.1.3 on 2024-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(default=None, help_text='Session ID for anonymous users', max_length=255),
            preserve_default=False,
        ),
    ]
