# Generated by Django 5.1.3 on 2024-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
