# Generated by Django 5.1.3 on 2024-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_orders_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
