# Generated by Django 5.1.3 on 2025-01-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_vendor_total_orders_vendor_total_orders_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
