# Generated by Django 5.1.3 on 2024-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount for the order', max_digits=10),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
