# Generated by Django 5.1.3 on 2024-11-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_session_id_cart_session'),
        ('orders', '0002_order_total_amount_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, help_text='The cart used for this order', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='carts.cart'),
        ),
    ]
