# Generated by Django 5.1.3 on 2024-11-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0, help_text='The total amount for the order'),
        ),
    ]
