# Generated by Django 5.1.3 on 2024-11-25 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('message', models.CharField(default=None, max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('unread', 'unread'), ('expired', 'expired'), ('read', 'read')], default='unread', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notification', to='customers.customer')),
            ],
        ),
    ]
