# Generated by Django 5.1.3 on 2025-01-11 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_1',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_2',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('New Arrivals', 'New Arrivals'), ('Black Friday', 'Black Friday'), ('Flashsales', 'Flashsales'), ('Special Offers', 'Special Offers'), ('Sponsored products', 'Sponsored products'), ('Deals of the day', 'Deals of the day')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Outdoor & Sports', 'Outdoor & Sports'), ('Electrical and Electronics', 'Electrical and Electronics'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Books & Education', 'Books & Education'), ('Interior Decorations', 'Interior Decorations'), ('Lightings & Chandeliars', 'Lightings & Chandeliars'), ('Exterior Decoratrions', 'Exterior Decoratrions'), ('Phone Accessories', 'Phone Accessories'), ('Phones & Tablets', 'Phones & Tablets'), ('Foodstuffs', 'Foodstuffs'), ('Health & Beauty', 'Health & Beauty'), ('Home & Office', 'Home & Office'), ('Gaming', 'Gaming'), ('Computing', 'Computing'), ('Kids and Toys', 'Kids and toys'), ('Fitness and Exercise', 'Fitness and Exercise'), ('Gadget and Accessories', 'Gadget and Accessories'), ('Baby care', 'Baby care'), ('Men Fashion', 'Men Fashion'), ('Men accessories', 'Men accessories'), ('Men skincare', 'Men Skincare'), ('Women Fashion', 'Women Fashion'), ('Women accessories', 'Women accessories'), ('Women skincare', 'women Skincare'), ('Kids skincare', 'Kids Skincare'), ('Kids Fashion', 'Kids Fashion'), ('Kids accessories', 'Kids accessories')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
