# Generated by Django 5.1.3 on 2025-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_brand_remove_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=125, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_price',
            field=models.CharField(default=None, max_length=125),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default=None, max_length=125),
        ),
    ]
